### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by GavinMai-tul33743** [cis3296f24/TrainTracker#112]
The website link works fine, but I could not download Node.js from the build instructions.

I used the link in step 3, opened my command prompt, and copy pasted the code from the link into the terminal. After following the terminal prompts, I expected to be able to continue to step 3.1, but I got an error that npm is not a recognized command.
I have a windows computer.

**Comment by ahgoldmeer** [comment]
Thats super weird...I'll probably change the link in the readme to use the prebuilt installer instead (just as a .msi file) so that future users can use the installer for node instead. Should be an easier way to install node. Thanks for bringing this up!
